# Generated by Django 3.2.5 on 2021-07-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentForm',
            new_name='Student',
        ),
    ]
